export const VALIDATOR_SIGNUP = "VALIDATOR_SIGNUP"
export const VALIDATOR_SIGNIN = "VALIDATOR_SIGNIN"
export const CREDENTIAL_VALIDATE = 'CREDENTIAL_VALIDATE'
export const CREDENTIAL_ERROR = 'CREDENTIAL_ERROR'